apiVersion: v1
kind: ConfigMap
metadata:
  name: incident-config
  namespace: incident-dashboard
data:
  HTTP_ADDR: ":8080"
  NATS_URL: "nats://nats.incident-dashboard.svc.cluster.local:4222"
  NATS_STREAM: "INCIDENTS"
  NATS_REPLICAS: "3"
  REQUEST_TIMEOUT: "2s"
  MAX_IN_FLIGHT: "20000"
  WORKER_BATCH_SIZE: "2000"
  WORKER_FETCH_WAIT: "250ms"
  SSE_CLIENT_BUFFER: "1024"
  CORS_ORIGIN: "*"
