import http from 'k6/http';
import { check, sleep } from 'k6';
import exec from 'k6/execution';

export const options = {
  scenarios: {
    ingest: {
      executor: 'ramping-arrival-rate',
      startRate: 100,
      timeUnit: '1s',
      preAllocatedVUs: 1000,
      maxVUs: 20000,
      stages: [
        { target: 1000, duration: '30s' },
        { target: 5000, duration: '1m' },
        { target: 10000, duration: '1m' },
        { target: 0, duration: '20s' }
      ]
    }
  },
  thresholds: {
    http_req_failed: ['rate<0.01'],
    http_req_duration: ['p(95)<250', 'p(99)<500']
  }
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
const TENANT_ID = __ENV.TENANT_ID || 'loadtest';

export default function () {
  const payload = JSON.stringify({
    title: `Synthetic incident ${exec.scenario.iterationInTest}`,
    description: 'Generated by k6 to test async ingestion path',
    severity: ['SEV1', 'SEV2', 'SEV3', 'SEV4'][Math.floor(Math.random() * 4)],
    service: 'synthetic-service',
    assignee: 'load-generator'
  });
  const res = http.post(`${BASE_URL}/v1/incidents`, payload, {
    headers: {
      'Content-Type': 'application/json',
      'X-Tenant-ID': TENANT_ID,
      'Idempotency-Key': `${__VU}-${__ITER}-${Date.now()}`
    },
    timeout: '3s'
  });
  check(res, {
    'accepted': (r) => r.status === 202
  });
  sleep(0.001);
}
